name: CI

permissions:
  contents: read

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Check out source
        uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6
      - name: Install Odin
        uses: laytan/setup-odin@8536d8fa450ec6f1bd9ddc84bbaaf16296c0051d # v2.12.2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          release: dev-2026-09
      - name: Test primitives
        run: odin test . -vet -strict-style
      - name: Test store conformance
        run: odin test ./conformance -vet -strict-style
